import type { Metadata } from "next";
import "./globals.css";
import "@/devlink/global.css";
import { DevLinkProvider } from "@/devlink";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from '@vercel/analytics/react';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="green">
        <DevLinkProvider>
          {children}
          <SpeedInsights />
          <Analytics />
        </DevLinkProvider>
      </body>
    </html>
  );
}
